const FILE_ICON_MAP: Record<string, { icon: string; color: string }> = {
  // Images
  jpg: { icon: "mdi:file-image", color: "text-purple-500" },
  jpeg: { icon: "mdi:file-image", color: "text-purple-500" },
  png: { icon: "mdi:file-image", color: "text-purple-500" },
  gif: { icon: "mdi:file-image", color: "text-purple-500" },
  bmp: { icon: "mdi:file-image", color: "text-purple-500" },
  svg: { icon: "mdi:file-image", color: "text-purple-500" },
  webp: { icon: "mdi:file-image", color: "text-purple-500" },
  ico: { icon: "mdi:file-image", color: "text-purple-500" },
  tiff: { icon: "mdi:file-image", color: "text-purple-500" },
  tif: { icon: "mdi:file-image", color: "text-purple-500" },
  avif: { icon: "mdi:file-image", color: "text-purple-500" },
  heic: { icon: "mdi:file-image", color: "text-purple-500" },
  heif: { icon: "mdi:file-image", color: "text-purple-500" },
  raw: { icon: "mdi:file-image", color: "text-purple-500" },
  psd: { icon: "mdi:file-image", color: "text-blue-400" },
  ai: { icon: "mdi:file-image", color: "text-orange-500" },
  // PDF
  pdf: { icon: "mdi:file-pdf-box", color: "text-red-500" },
  // Documents
  doc: { icon: "mdi:file-word", color: "text-blue-600" },
  docx: { icon: "mdi:file-word", color: "text-blue-600" },
  odt: { icon: "mdi:file-word", color: "text-blue-600" },
  rtf: { icon: "mdi:file-word", color: "text-blue-600" },
  // Spreadsheets
  xls: { icon: "mdi:file-excel", color: "text-green-600" },
  xlsx: { icon: "mdi:file-excel", color: "text-green-600" },
  csv: { icon: "mdi:file-excel", color: "text-green-600" },
  ods: { icon: "mdi:file-excel", color: "text-green-600" },
  tsv: { icon: "mdi:file-excel", color: "text-green-600" },
  // Presentations
  ppt: { icon: "mdi:file-powerpoint", color: "text-orange-600" },
  pptx: { icon: "mdi:file-powerpoint", color: "text-orange-600" },
  odp: { icon: "mdi:file-powerpoint", color: "text-orange-600" },
  key: { icon: "mdi:file-powerpoint", color: "text-orange-600" },
  // Video
  mp4: { icon: "mdi:file-video", color: "text-pink-500" },
  avi: { icon: "mdi:file-video", color: "text-pink-500" },
  mov: { icon: "mdi:file-video", color: "text-pink-500" },
  mkv: { icon: "mdi:file-video", color: "text-pink-500" },
  wmv: { icon: "mdi:file-video", color: "text-pink-500" },
  flv: { icon: "mdi:file-video", color: "text-pink-500" },
  webm: { icon: "mdi:file-video", color: "text-pink-500" },
  m4v: { icon: "mdi:file-video", color: "text-pink-500" },
  "3gp": { icon: "mdi:file-video", color: "text-pink-500" },
  // Audio
  mp3: { icon: "mdi:file-music", color: "text-teal-500" },
  wav: { icon: "mdi:file-music", color: "text-teal-500" },
  flac: { icon: "mdi:file-music", color: "text-teal-500" },
  aac: { icon: "mdi:file-music", color: "text-teal-500" },
  ogg: { icon: "mdi:file-music", color: "text-teal-500" },
  wma: { icon: "mdi:file-music", color: "text-teal-500" },
  m4a: { icon: "mdi:file-music", color: "text-teal-500" },
  opus: { icon: "mdi:file-music", color: "text-teal-500" },
  mid: { icon: "mdi:file-music", color: "text-teal-500" },
  midi: { icon: "mdi:file-music", color: "text-teal-500" },
  // Archives
  zip: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  rar: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  "7z": { icon: "mdi:folder-zip", color: "text-yellow-600" },
  tar: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  gz: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  bz2: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  xz: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  zst: { icon: "mdi:folder-zip", color: "text-yellow-600" },
  iso: { icon: "mdi:disc", color: "text-yellow-600" },
  dmg: { icon: "mdi:disc", color: "text-yellow-600" },
  // Code
  js: { icon: "mdi:language-javascript", color: "text-yellow-400" },
  mjs: { icon: "mdi:language-javascript", color: "text-yellow-400" },
  cjs: { icon: "mdi:language-javascript", color: "text-yellow-400" },
  ts: { icon: "mdi:language-typescript", color: "text-blue-500" },
  tsx: { icon: "mdi:language-typescript", color: "text-blue-500" },
  jsx: { icon: "mdi:language-javascript", color: "text-yellow-400" },
  py: { icon: "mdi:language-python", color: "text-blue-400" },
  java: { icon: "mdi:language-java", color: "text-red-400" },
  kt: { icon: "mdi:language-kotlin", color: "text-purple-400" },
  swift: { icon: "mdi:language-swift", color: "text-orange-500" },
  c: { icon: "mdi:language-c", color: "text-blue-500" },
  cpp: { icon: "mdi:language-cpp", color: "text-blue-600" },
  h: { icon: "mdi:language-c", color: "text-blue-500" },
  hpp: { icon: "mdi:language-cpp", color: "text-blue-600" },
  cs: { icon: "mdi:language-csharp", color: "text-green-500" },
  go: { icon: "mdi:language-go", color: "text-cyan-500" },
  rs: { icon: "mdi:language-rust", color: "text-orange-700" },
  rb: { icon: "mdi:language-ruby", color: "text-red-500" },
  php: { icon: "mdi:language-php", color: "text-indigo-400" },
  lua: { icon: "mdi:language-lua", color: "text-blue-600" },
  r: { icon: "mdi:language-r", color: "text-blue-400" },
  dart: { icon: "mdi:code-braces", color: "text-cyan-500" },
  scala: { icon: "mdi:code-braces", color: "text-red-500" },
  // Web
  html: { icon: "mdi:language-html5", color: "text-orange-500" },
  htm: { icon: "mdi:language-html5", color: "text-orange-500" },
  css: { icon: "mdi:language-css3", color: "text-blue-500" },
  scss: { icon: "mdi:language-css3", color: "text-pink-400" },
  sass: { icon: "mdi:language-css3", color: "text-pink-400" },
  less: { icon: "mdi:language-css3", color: "text-blue-400" },
  vue: { icon: "mdi:vuejs", color: "text-green-500" },
  // Data / Config
  json: { icon: "mdi:code-json", color: "text-yellow-500" },
  jsonc: { icon: "mdi:code-json", color: "text-yellow-500" },
  xml: { icon: "mdi:file-xml-box", color: "text-orange-400" },
  yaml: { icon: "mdi:file-code", color: "text-red-400" },
  yml: { icon: "mdi:file-code", color: "text-red-400" },
  toml: { icon: "mdi:file-code", color: "text-gray-500" },
  ini: { icon: "mdi:file-cog", color: "text-gray-500" },
  env: { icon: "mdi:file-cog", color: "text-yellow-600" },
  // Shell / Scripts
  sh: { icon: "mdi:console", color: "text-green-400" },
  bash: { icon: "mdi:console", color: "text-green-400" },
  zsh: { icon: "mdi:console", color: "text-green-400" },
  bat: { icon: "mdi:console", color: "text-gray-500" },
  cmd: { icon: "mdi:console", color: "text-gray-500" },
  ps1: { icon: "mdi:powershell", color: "text-blue-500" },
  // Text / Docs
  txt: { icon: "mdi:file-document-outline", color: "text-gray-500" },
  md: { icon: "mdi:language-markdown", color: "text-gray-600" },
  mdx: { icon: "mdi:language-markdown", color: "text-gray-600" },
  log: { icon: "mdi:file-document-outline", color: "text-gray-400" },
  // Database
  sql: { icon: "mdi:database", color: "text-blue-400" },
  db: { icon: "mdi:database", color: "text-blue-400" },
  sqlite: { icon: "mdi:database", color: "text-blue-400" },
  // Fonts
  ttf: { icon: "mdi:format-font", color: "text-gray-500" },
  otf: { icon: "mdi:format-font", color: "text-gray-500" },
  woff: { icon: "mdi:format-font", color: "text-gray-500" },
  woff2: { icon: "mdi:format-font", color: "text-gray-500" },
  eot: { icon: "mdi:format-font", color: "text-gray-500" },
  // Executables / Binaries
  exe: { icon: "mdi:application-cog", color: "text-gray-600" },
  msi: { icon: "mdi:application-cog", color: "text-gray-600" },
  deb: { icon: "mdi:application-cog", color: "text-gray-600" },
  rpm: { icon: "mdi:application-cog", color: "text-gray-600" },
  apk: { icon: "mdi:android", color: "text-green-500" },
  ipa: { icon: "mdi:apple", color: "text-gray-600" },
  // 3D / CAD
  obj: { icon: "mdi:cube-outline", color: "text-orange-400" },
  stl: { icon: "mdi:cube-outline", color: "text-orange-400" },
  fbx: { icon: "mdi:cube-outline", color: "text-orange-400" },
  gltf: { icon: "mdi:cube-outline", color: "text-orange-400" },
  glb: { icon: "mdi:cube-outline", color: "text-orange-400" },
  // Misc
  lock: { icon: "mdi:file-lock", color: "text-gray-500" },
  bak: { icon: "mdi:file-restore", color: "text-gray-400" },
  tmp: { icon: "mdi:file-clock", color: "text-gray-400" },
  torrent: { icon: "mdi:magnet", color: "text-green-500" },
};

const DEFAULT_FILE_ICON = { icon: "mdi:file-outline", color: "text-info" };

export function getFileIcon(filename: string): { icon: string; color: string } {
  const ext =
    filename.lastIndexOf(".") !== -1
      ? filename.slice(filename.lastIndexOf(".") + 1).toLowerCase()
      : "";
  return FILE_ICON_MAP[ext] ?? DEFAULT_FILE_ICON;
}
